# Dependencies
markdown:         kramdown
#highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            蜗牛
tagline:          '从这里出初江湖，携手仗剑江湖路'
description:      '我要一步一步往上爬  只待阳光静静看着它的脸   小小的天 有大大的梦想 重重的壳裹着轻轻的仰望  我要一步一步往上爬'
baseurl:           /wuer-sBlog
author:
name:           'BigCow' 
url:            https://a1364533187.github.io/wuer-sBlog/
excerpt_separator: "\n\n\n"

paginate:        5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : BigCow
